name: teleportauth
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  google_sign_in: ^6.2.1
  otp_input_field: ^1.0.1
  flutter_riverpod: ^2.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.0.0
  intl: ^0.18.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
    - family: MuseoSans-500
      fonts: 
        - asset: assets/fonts/MuseoSans500.ttf
          weight: 400
